# Generated by Django 2.2.28 on 2025-03-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopSphere', '0003_auto_20250214_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
