# Generated by Django 2.2.28 on 2025-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopSphere', '0006_auto_20250320_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
